#!/bin/bash
set -e

echo "🚀 Building DXT file..."

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if DXT CLI is installed
if ! command -v dxt &> /dev/null; then
    echo -e "${BLUE}📦 Installing DXT CLI...${NC}"
    npm install -g @anthropic-ai/dxt || {
        echo -e "${RED}❌ Failed to install DXT CLI${NC}"
        exit 1
    }
fi

# The DXT is bundled into the worker source rather than served as a static
# asset (see comment below). Build to dist/, not public/, so wrangler's
# asset binding doesn't intercept the path before the worker handler runs.
mkdir -p dist
DXT_OUTPUT="dist/absmartly-mcp.dxt"

# Remove any stale copy from public/ (legacy asset-served location).
rm -f public/absmartly-mcp.dxt

echo -e "${BLUE}🔨 Building DXT extension into ${DXT_OUTPUT}...${NC}"
dxt pack . "$DXT_OUTPUT" || {
    echo -e "${RED}❌ Failed to build DXT file${NC}"
    exit 1
}

if [ ! -f "$DXT_OUTPUT" ]; then
    echo -e "${RED}❌ DXT file not found after build${NC}"
    exit 1
fi

# Embed the DXT bytes into the worker source so they ship with the worker
# version atomically. Wrangler's static asset binding is unreliable for newly
# uploaded files (cloudflare/workers-sdk#9157): the worker version is
# published referencing a stale asset manifest and the file 404s after edge
# cache evicts. Bundling guarantees the served bytes match the deployed code.
DXT_B64=$(base64 < "$DXT_OUTPUT" | tr -d '\n')
DXT_SHA=$(shasum "$DXT_OUTPUT" | cut -d' ' -f1)
DXT_SIZE=$(wc -c < "$DXT_OUTPUT" | tr -d ' ')

cat > src/dxt-bundle.ts <<EOF
// AUTO-GENERATED by scripts/build-dxt.sh — do not edit by hand.
// Regenerated whenever the DXT is rebuilt.
export const DXT_BUNDLE_BASE64 = "${DXT_B64}";
export const DXT_BUNDLE_SHA = "${DXT_SHA}";
export const DXT_BUNDLE_SIZE = ${DXT_SIZE};
EOF

echo -e "${GREEN}✅ DXT built at ${DXT_OUTPUT} (${DXT_SIZE} bytes, SHA ${DXT_SHA:0:12})${NC}"
echo -e "${GREEN}✅ Worker bundle source written to src/dxt-bundle.ts${NC}"
echo -e "${GREEN}📥 Download URL after deploy: https://mcp.absmartly.com/absmartly-mcp.dxt${NC}"