#!/usr/bin/env bash
# Writes a minimal src/dxt-bundle.ts stub when the real file does not exist.
#
# scripts/build-dxt.sh generates src/dxt-bundle.ts during local `npm run deploy`,
# embedding the packed DXT bytes into the worker source. The file is gitignored
# (so the giant base64 blob does not pollute diffs), which means it is absent
# in CI checkouts. Without it `tsc --noEmit` fails with TS2307 on the import
# in src/index.ts, blocking every PR build.
#
# This script writes a stub with empty exports so typecheck and unit tests run
# in CI. It must not be wired into the deploy workflow — deploying with an
# empty bundle would serve broken bytes from the worker's `/absmartly-mcp.dxt`
# route. Production deploys go through `npm run deploy` locally, which calls
# scripts/build-dxt.sh and overwrites the stub with real bytes.
set -e

STUB_PATH="src/dxt-bundle.ts"

if [ -f "$STUB_PATH" ]; then
    echo "$STUB_PATH already exists, leaving it alone"
    exit 0
fi

echo "$STUB_PATH not found, writing CI stub"
cat > "$STUB_PATH" <<'EOF'
// CI-only stub written by scripts/ensure-dxt-bundle.sh.
// The real bundle is regenerated by scripts/build-dxt.sh during `npm run deploy`.
export const DXT_BUNDLE_BASE64 = "";
export const DXT_BUNDLE_SHA = "";
export const DXT_BUNDLE_SIZE = 0;
EOF
