// Shape of endpoint-manifest.json (exported as "@absmartly/mcp/endpoint-manifest.json"),
// generated by scripts/endpoint-manifest.ts from the tool definitions and the
// installed @absmartly/cli build. A host asserts each `endpoints` entry exists
// in its OpenAPI spec so a backend route change cannot silently break a tool.

export type EndpointHttpMethod = "GET" | "POST" | "PUT" | "DELETE";

export interface Endpoint {
  method: EndpointHttpMethod;
  /** Full server path, e.g. /v1/experiments/{id} or /auth/current-user. Parameter names are not significant. */
  path: string;
}

export interface EndpointManifest {
  manifestVersion: 1;
  generatedFrom: { "@absmartly/cli": string };
  /** Union of every endpoint below; the list a host asserts against its OpenAPI spec. */
  endpoints: Endpoint[];
  tools: Record<string, { endpoints: Endpoint[] }>;
  resources: Record<string, { endpoints: Endpoint[] }>;
  /** Keyed by "<group>.<command>", the execute_command arguments. */
  commands: Record<string, { apiMethods: string[]; endpoints: Endpoint[] }>;
  /** APIClient methods whose path is built at runtime (not in `endpoints`). */
  dynamicApiMethods: string[];
}
